"""Added saving goal

Revision ID: 733db79fc0b1
Revises: 01310bca0b45
Create Date: 2024-07-24 12:10:07.483531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '733db79fc0b1'
down_revision = '01310bca0b45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.add_column(sa.Column('savings_goal', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.drop_column('savings_goal')

    # ### end Alembic commands ###
